import type { QuizQuestion } from "@/components/interactive/MultipleChoiceQuiz";

export const reviewQuestionCount = 10;

const supplementalReviewQuestions: Record<string, QuizQuestion[]> = {
  logic: [
    {
      prompt: "`not (P or Q)`와 가장 가까운 읽기는?",
      choices: ["P도 아니고 Q도 아니다.", "P이거나 Q이다.", "P이고 Q이다.", "P이면 Q이다."],
      correctIndex: 0,
      explanation: "OR 전체를 부정하면 두 조건이 모두 거짓이어야 합니다.",
      conceptTags: ["부정", "OR"],
      questionType: "negation",
    },
    {
      prompt: "`is_admin or is_owner`가 참이 되는 경우는?",
      choices: ["둘 중 하나라도 참일 때", "둘 다 반드시 참일 때", "둘 다 거짓일 때", "항상 거짓일 때"],
      correctIndex: 0,
      explanation: "OR는 둘 중 하나라도 참이면 전체가 참입니다.",
      conceptTags: ["논리 연산", "OR"],
      questionType: "operator-reading",
    },
  ],
  conditionals: [
    {
      prompt: "$P \\to Q$의 대우는?",
      choices: ["$\\lnot Q \\to \\lnot P$", "$Q \\to P$", "$\\lnot P \\to \\lnot Q$", "$P \\land Q$"],
      correctIndex: 0,
      explanation: "조건문의 대우는 결론을 부정해 앞에 두고, 앞조건을 부정해 뒤에 둡니다.",
      conceptTags: ["조건문", "대우"],
      questionType: "contrapositive",
    },
    {
      prompt: "\"테스트가 통과하면 배포한다\"에서 결론 Q는?",
      choices: ["배포한다", "테스트가 통과한다", "테스트가 실패한다", "배포하지 않는다"],
      correctIndex: 0,
      explanation: "P -> Q에서 '그러면' 뒤에 오는 내용이 결론 Q입니다.",
      conceptTags: ["조건문", "앞조건과 결론"],
      questionType: "condition-parts",
    },
  ],
  sets: [
    {
      prompt: "권한 검사에서 `required <= granted`가 뜻하는 것은?",
      choices: ["필요한 권한이 모두 부여되어 있다.", "부여된 권한을 모두 삭제한다.", "두 권한 집합을 합친다.", "필요한 권한이 하나도 없다."],
      correctIndex: 0,
      explanation: "부분집합 검사는 required의 모든 원소가 granted에 포함되는지 확인합니다.",
      conceptTags: ["부분집합", "권한 검사"],
      questionType: "subset-code",
    },
    {
      prompt: "방문한 URL을 `visited` 집합에 저장하는 주된 이유는?",
      choices: ["이미 처리한 대상을 빠르게 확인하기 위해", "URL 순서를 보존하기 위해", "모든 URL을 두 번 방문하기 위해", "문자열을 정렬하기 위해"],
      correctIndex: 0,
      explanation: "집합은 포함 여부를 확인하고 중복 처리를 막는 데 자주 쓰입니다.",
      conceptTags: ["집합", "방문 집합"],
      questionType: "cs-context",
    },
  ],
  functions: [
    {
      prompt: "정의역의 한 원소가 두 출력으로 동시에 연결되면?",
      choices: ["함수 조건을 깨뜨린다.", "항상 전사함수다.", "항상 일대일함수다.", "공역이 사라진다."],
      correctIndex: 0,
      explanation: "함수는 정의역의 각 원소가 정확히 하나의 출력으로 가야 합니다.",
      conceptTags: ["함수 조건"],
      questionType: "function-rule",
    },
    {
      prompt: "치역을 확인할 때 보는 것은?",
      choices: ["실제로 나온 출력값", "나올 수 있다고 정한 전체 후보", "입력값의 이름", "함수 코드 줄 수"],
      correctIndex: 0,
      explanation: "치역은 공역 중 실제로 대응되어 나온 값들의 집합입니다.",
      conceptTags: ["치역", "공역"],
      questionType: "range-codomain",
    },
    {
      prompt: "`x -> x % 2`를 짝수 입력에만 적용하면 실제 출력은?",
      choices: ["0만 나온다.", "0과 1이 모두 나온다.", "입력과 항상 같다.", "항상 2가 나온다."],
      correctIndex: 0,
      explanation: "짝수를 2로 나눈 나머지는 항상 0입니다.",
      conceptTags: ["함수", "치역"],
      questionType: "code-function",
    },
  ],
  induction: [
    {
      prompt: "귀납법에서 귀납 가정은 보통 무엇을 가정하는가?",
      choices: ["n = k에서 명제가 참이라고 둔다.", "모든 n을 계산기로 확인한다.", "기저 사례를 생략한다.", "반례가 있다고 둔다."],
      correctIndex: 0,
      explanation: "귀납 단계에서는 보통 n = k에서 참이라고 가정하고 n = k + 1을 보입니다.",
      conceptTags: ["귀납 가정"],
      questionType: "induction-hypothesis",
    },
    {
      prompt: "재귀 함수가 종료됨을 설명할 때 귀납법과 가장 닮은 부분은?",
      choices: ["작은 입력으로 내려간다는 점", "변수 이름이 짧다는 점", "출력이 문자열이라는 점", "반복문이 없다는 점"],
      correctIndex: 0,
      explanation: "재귀가 작은 입력으로 내려가 기저 사례에 도달한다는 구조가 귀납법과 닮았습니다.",
      conceptTags: ["재귀", "귀납법"],
      questionType: "recursion-induction",
    },
    {
      prompt: "귀납 단계만 있고 기저 사례가 없으면?",
      choices: ["출발점이 없어 전체 증명이 완성되지 않는다.", "항상 더 강한 증명이 된다.", "자동으로 참이다.", "반례가 필요 없다."],
      correctIndex: 0,
      explanation: "기저 사례는 첫 번째 발판입니다. 없으면 귀납 사슬을 시작할 수 없습니다.",
      conceptTags: ["기저 사례"],
      questionType: "base-case",
    },
  ],
  counting: [
    {
      prompt: "순서가 중요한 선택은 보통 무엇과 가깝나?",
      choices: ["순열", "조합", "교집합", "동치관계"],
      correctIndex: 0,
      explanation: "같은 대상을 골라도 순서나 역할이 달라지면 순열 관점이 맞습니다.",
      conceptTags: ["순열", "순서"],
      questionType: "permutation",
    },
    {
      prompt: "서로 독립적인 선택지가 3개와 4개라면 전체 경우의 수는?",
      choices: ["12", "7", "1", "34"],
      correctIndex: 0,
      explanation: "곱의 법칙에 따라 3 * 4 = 12가지입니다.",
      conceptTags: ["곱의 법칙"],
      questionType: "product-rule",
    },
    {
      prompt: "완전 탐색 전에 경우의 수를 세는 가장 실용적인 이유는?",
      choices: ["시간 안에 가능한지 가늠하기 위해", "정렬을 생략하기 위해", "메모리를 항상 0으로 만들기 위해", "입력을 숨기기 위해"],
      correctIndex: 0,
      explanation: "탐색 공간 크기를 알아야 풀이가 현실적인지 판단할 수 있습니다.",
      conceptTags: ["완전 탐색", "경우의 수"],
      questionType: "search-space",
    },
  ],
  graphs: [
    {
      prompt: "무방향 그래프의 간선 A-B는 보통 어떻게 읽나?",
      choices: ["A와 B가 서로 연결되어 있다.", "A에서 B로만 갈 수 있다.", "B에서 A로만 갈 수 있다.", "A와 B가 같은 정점이다."],
      correctIndex: 0,
      explanation: "무방향 간선은 방향 없이 두 정점이 연결되어 있음을 뜻합니다.",
      conceptTags: ["그래프", "무방향 간선"],
      questionType: "edge-reading",
    },
    {
      prompt: "인접 리스트가 특히 잘 나타내는 것은?",
      choices: ["각 정점에서 바로 갈 수 있는 이웃", "정점 이름의 길이", "간선의 색상", "그래프 파일 크기"],
      correctIndex: 0,
      explanation: "인접 리스트는 정점별 이웃 목록을 저장하는 표현입니다.",
      conceptTags: ["인접 리스트"],
      questionType: "graph-representation",
    },
    {
      prompt: "그래프 탐색에서 큐를 쓰면 보통 어떤 탐색과 가까운가?",
      choices: ["BFS", "DFS", "정렬", "해싱"],
      correctIndex: 0,
      explanation: "BFS는 먼저 발견한 정점을 먼저 처리하므로 큐와 잘 맞습니다.",
      conceptTags: ["BFS", "큐"],
      questionType: "traversal",
    },
  ],
  relations: [
    {
      prompt: "관계를 순서쌍으로 볼 때 `(a, b)`는 무엇을 뜻하나?",
      choices: ["a가 b와 관계가 있다.", "a와 b가 항상 같다.", "b가 a보다 작다.", "a가 집합이 아니다."],
      correctIndex: 0,
      explanation: "순서쌍 (a, b)는 a에서 b로 관계가 있음을 나타냅니다.",
      conceptTags: ["관계", "순서쌍"],
      questionType: "ordered-pair",
    },
    {
      prompt: "반사성을 검사할 때 모든 원소 x에 대해 필요한 것은?",
      choices: ["(x, x)가 관계에 있다.", "(x, y)가 항상 없다.", "(y, x)가 항상 없다.", "x가 숫자다."],
      correctIndex: 0,
      explanation: "반사성은 각 원소가 자기 자신과 관계가 있어야 합니다.",
      conceptTags: ["반사성"],
      questionType: "reflexive",
    },
    {
      prompt: "A가 B를 팔로우한다고 B도 A를 팔로우해야 한다고 볼 수 없는 성질은?",
      choices: ["대칭성", "반사성", "추이성", "전사성"],
      correctIndex: 0,
      explanation: "대칭성은 (a, b)가 있으면 (b, a)도 있어야 한다는 성질입니다.",
      conceptTags: ["대칭성"],
      questionType: "symmetric",
    },
  ],
  "proof-techniques": [
    {
      prompt: "반례를 찾았을 때 바로 반박되는 주장은?",
      choices: ["모든 x에 대해 성립한다는 주장", "어떤 x 하나가 존재한다는 주장", "정의역이 비어 있다는 주장", "기호를 쓰지 않은 주장"],
      correctIndex: 0,
      explanation: "전칭 명제는 반례 하나로 거짓임을 보일 수 있습니다.",
      conceptTags: ["반례", "전칭 명제"],
      questionType: "counterexample",
    },
    {
      prompt: "모순 증명은 보통 무엇을 가정하고 시작하나?",
      choices: ["보이고 싶은 결론의 부정", "항상 참인 결론", "아무 조건도 없음", "예시 하나"],
      correctIndex: 0,
      explanation: "모순 증명은 결론이 거짓이라고 가정한 뒤 모순을 이끌어냅니다.",
      conceptTags: ["모순 증명"],
      questionType: "contradiction",
    },
    {
      prompt: "대우 증명이 유용한 경우는?",
      choices: ["원래 조건보다 결론의 부정에서 출발하기 쉬울 때", "반례가 이미 있을 때", "명제가 존재 명제일 때만", "기저 사례가 없을 때"],
      correctIndex: 0,
      explanation: "P -> Q 대신 not Q -> not P가 더 자연스럽게 보일 때 대우 증명을 씁니다.",
      conceptTags: ["대우 증명"],
      questionType: "contrapositive-proof",
    },
  ],
  "logical-equivalence": [
    {
      prompt: "$P \\land Q$와 $Q \\land P$의 관계는?",
      choices: ["논리적으로 동치이다.", "항상 반대이다.", "P가 참일 때만 다르다.", "비교할 수 없다."],
      correctIndex: 0,
      explanation: "AND는 순서를 바꾸어도 진리값이 같습니다.",
      conceptTags: ["논리적 동치", "교환법칙"],
      questionType: "equivalence-law",
    },
    {
      prompt: "`not (a or b)`를 코드 조건으로 바꿀 때 가장 가까운 것은?",
      choices: ["`not a and not b`", "`not a or not b`", "`a and b`", "`a or b`"],
      correctIndex: 0,
      explanation: "드모르간 법칙에 따라 OR의 부정은 각 항의 부정을 AND로 묶습니다.",
      conceptTags: ["드모르간 법칙"],
      questionType: "de-morgan",
    },
    {
      prompt: "$P \\to Q$를 OR로 바꾸면?",
      choices: ["$\\lnot P \\lor Q$", "$P \\lor Q$", "$P \\land Q$", "$\\lnot Q \\lor P$"],
      correctIndex: 0,
      explanation: "조건문 P -> Q는 not P 또는 Q와 동치입니다.",
      conceptTags: ["조건문 동치"],
      questionType: "implication-equivalence",
    },
    {
      prompt: "조건식을 리팩터링한 뒤 동치 확인이 필요한 이유는?",
      choices: ["모든 입력에서 같은 결과를 내야 하기 때문", "코드 줄 수가 같아야 하기 때문", "변수 이름이 같아야 하기 때문", "주석이 줄어야 하기 때문"],
      correctIndex: 0,
      explanation: "리팩터링은 표현만 바꾸고 동작은 유지해야 합니다.",
      conceptTags: ["조건식 리팩터링"],
      questionType: "refactoring",
    },
  ],
  "predicate-logic": [
    {
      prompt: "`all(...)`이 빈 리스트에서 참이 되는 것과 가까운 수량자 해석은?",
      choices: ["전칭 명제의 공허한 참", "존재 명제의 거짓", "항상 오류", "부분순서"],
      correctIndex: 0,
      explanation: "반례가 없으면 전칭 조건은 깨지지 않은 것으로 봅니다.",
      conceptTags: ["전칭", "공허한 참"],
      questionType: "vacuous-truth",
    },
    {
      prompt: "$\\exists x P(x)$가 참이라는 뜻은?",
      choices: ["P를 만족하는 x가 적어도 하나 있다.", "모든 x가 P를 만족한다.", "어떤 x도 P를 만족하지 않는다.", "x가 숫자여야 한다."],
      correctIndex: 0,
      explanation: "존재 수량자는 조건을 만족하는 대상이 하나 이상 있음을 뜻합니다.",
      conceptTags: ["존재 수량자"],
      questionType: "existential",
    },
    {
      prompt: "$\\forall x \\exists y R(x, y)$에서 먼저 고르는 대상은?",
      choices: ["임의의 x", "하나의 y만", "항상 같은 x", "관계 R의 이름"],
      correctIndex: 0,
      explanation: "바깥 수량자인 forall x부터 읽고, 각 x에 대해 y가 존재하는지 봅니다.",
      conceptTags: ["중첩 수량자"],
      questionType: "nested-quantifier",
    },
    {
      prompt: "`any(user.active for user in users)`와 가까운 말은?",
      choices: ["활성 사용자가 적어도 한 명 있다.", "모든 사용자가 활성이다.", "활성 사용자가 없다.", "사용자 수가 0이다."],
      correctIndex: 0,
      explanation: "any는 조건을 만족하는 원소가 하나라도 있는지 확인합니다.",
      conceptTags: ["존재 수량자", "any"],
      questionType: "code-quantifier",
    },
    {
      prompt: "$\\lnot \\exists x P(x)$와 동치인 것은?",
      choices: ["$\\forall x \\lnot P(x)$", "$\\exists x \\lnot P(x)$", "$\\forall x P(x)$", "$P(x)$"],
      correctIndex: 0,
      explanation: "존재하지 않는다는 말은 모든 대상이 P를 만족하지 않는다는 뜻입니다.",
      conceptTags: ["수량자 부정"],
      questionType: "quantifier-negation",
    },
    {
      prompt: "술어 논리를 코드 필터와 연결할 때 먼저 정해야 하는 것은?",
      choices: ["대상 집합과 조건 P(x)", "폰트 크기", "파일 확장자", "정렬 알고리즘"],
      correctIndex: 0,
      explanation: "어떤 대상들에 대해 어떤 조건을 검사하는지 정해야 수량자를 해석할 수 있습니다.",
      conceptTags: ["술어", "코드 필터"],
      questionType: "predicate-modeling",
    },
  ],
  "equivalence-relations": [
    {
      prompt: "동치류끼리는 어떤 관계인가?",
      choices: ["서로 같거나 겹치지 않는다.", "항상 하나의 원소만 가진다.", "항상 무한하다.", "순서를 만든다."],
      correctIndex: 0,
      explanation: "동치관계가 만드는 동치류들은 전체 집합을 겹치지 않게 나눕니다.",
      conceptTags: ["동치류", "분할"],
      questionType: "equivalence-class",
    },
    {
      prompt: "같은 나머지를 갖는다는 관계가 동치관계인 이유와 가장 가까운 것은?",
      choices: ["반사성, 대칭성, 추이성을 만족하기 때문", "항상 크기 순서를 만들기 때문", "모든 수가 서로 다르기 때문", "간선이 없기 때문"],
      correctIndex: 0,
      explanation: "같은 나머지 관계는 세 동치관계 성질을 만족합니다.",
      conceptTags: ["동치관계", "모듈러"],
      questionType: "mod-equivalence",
    },
    {
      prompt: "동치관계가 데이터 분류와 연결되는 방식은?",
      choices: ["같은 기준의 대상을 같은 묶음으로 나눈다.", "모든 데이터를 한 줄로 정렬한다.", "중복을 반드시 제거하지 않는다.", "항상 그래프를 끊는다."],
      correctIndex: 0,
      explanation: "동치관계는 같은 것으로 볼 대상을 묶어 분류를 만듭니다.",
      conceptTags: ["분류", "동치관계"],
      questionType: "classification",
    },
    {
      prompt: "동치관계에서 대칭성이 뜻하는 것은?",
      choices: ["a가 b와 같게 분류되면 b도 a와 같게 분류된다.", "a는 항상 a보다 작다.", "a와 b가 연결되면 b와 c도 연결된다.", "모든 원소가 하나뿐이다."],
      correctIndex: 0,
      explanation: "대칭성은 관계의 방향을 바꾸어도 성립해야 한다는 조건입니다.",
      conceptTags: ["대칭성", "동치관계"],
      questionType: "symmetric",
    },
    {
      prompt: "동치관계에서 추이성이 깨지는 상황은?",
      choices: ["a~b이고 b~c인데 a~c가 아닐 때", "a~a가 있을 때", "a~b이면 b~a일 때", "모든 원소가 분류될 때"],
      correctIndex: 0,
      explanation: "추이성은 a~b, b~c이면 a~c가 되어야 합니다.",
      conceptTags: ["추이성", "동치관계"],
      questionType: "transitive",
    },
    {
      prompt: "분할에서 각 원소가 가져야 하는 성질은?",
      choices: ["정확히 하나의 블록에 속한다.", "모든 블록에 동시에 속한다.", "어떤 블록에도 속하지 않는다.", "항상 첫 블록에만 속한다."],
      correctIndex: 0,
      explanation: "분할은 전체를 빠짐없이, 겹치지 않게 나누는 구조입니다.",
      conceptTags: ["분할"],
      questionType: "partition",
    },
  ],
  "partial-orders": [
    {
      prompt: "부분순서에서 반대칭성이 말하는 것은?",
      choices: ["a ≤ b이고 b ≤ a이면 a = b이다.", "모든 두 원소가 비교 가능하다.", "a ≤ a가 항상 거짓이다.", "관계가 항상 대칭이다."],
      correctIndex: 0,
      explanation: "반대칭성은 양방향으로 관계가 성립하면 두 대상이 같아야 한다는 조건입니다.",
      conceptTags: ["반대칭성", "부분순서"],
      questionType: "antisymmetric",
    },
    {
      prompt: "작업 의존성에서 사이클이 문제인 이유는?",
      choices: ["서로 먼저 끝나야 하는 모순이 생기기 때문", "작업 수가 줄기 때문", "모든 작업이 독립이기 때문", "정렬이 항상 하나뿐이기 때문"],
      correctIndex: 0,
      explanation: "사이클은 A 전에 B, B 전에 A 같은 의존성 모순을 만듭니다.",
      conceptTags: ["DAG", "의존성"],
      questionType: "dependency-cycle",
    },
    {
      prompt: "전체순서가 부분순서보다 강한 점은?",
      choices: ["모든 두 원소가 비교 가능하다.", "반사성이 없다.", "추이성이 없다.", "항상 사이클이 있다."],
      correctIndex: 0,
      explanation: "전체순서에서는 임의의 두 원소를 항상 비교할 수 있습니다.",
      conceptTags: ["전체순서", "부분순서"],
      questionType: "total-order",
    },
    {
      prompt: "하세 도표에서 보통 생략하는 관계는?",
      choices: ["추이성으로 따라오는 간접 관계", "모든 직접 관계", "모든 정점", "최소 원소"],
      correctIndex: 0,
      explanation: "하세 도표는 핵심 직접 관계만 남기고 추이적으로 알 수 있는 간선은 생략합니다.",
      conceptTags: ["하세 도표"],
      questionType: "hasse",
    },
    {
      prompt: "부분순서가 정렬 작업과 연결되는 대표 예는?",
      choices: ["의존성을 만족하는 작업 순서 찾기", "문자열 길이 세기", "중복 원소 제거", "난수 생성"],
      correctIndex: 0,
      explanation: "작업 의존성은 부분순서로 보고 가능한 실행 순서를 찾을 수 있습니다.",
      conceptTags: ["부분순서", "위상 정렬"],
      questionType: "cs-connection",
    },
    {
      prompt: "부분순서에서 비교 불가능하다는 말은?",
      choices: ["두 원소 사이 어느 방향 관계도 정해지지 않았다.", "두 원소가 같다.", "항상 오류다.", "둘 다 집합이 아니다."],
      correctIndex: 0,
      explanation: "부분순서에서는 모든 원소 쌍이 비교 가능할 필요가 없습니다.",
      conceptTags: ["비교 불가능"],
      questionType: "incomparable",
    },
  ],
  "inclusion-exclusion": [
    {
      prompt: "|A| = 8, |B| = 7, |A ∩ B| = 3이면 |A ∪ B|는?",
      choices: ["12", "15", "18", "3"],
      correctIndex: 0,
      explanation: "|A ∪ B| = |A| + |B| - |A ∩ B| = 8 + 7 - 3 = 12입니다.",
      conceptTags: ["포함배제"],
      questionType: "calculation",
    },
    {
      prompt: "두 조건 중 하나라도 만족하는 항목 수를 셀 때 필요한 관점은?",
      choices: ["합집합 크기", "교집합만", "차집합만", "순열"],
      correctIndex: 0,
      explanation: "둘 중 하나라도 만족하면 두 집합의 합집합을 세는 문제입니다.",
      conceptTags: ["합집합", "포함배제"],
      questionType: "union-counting",
    },
    {
      prompt: "A와 B에 모두 속한 원소를 두 번 세는 상황은?",
      choices: ["|A|와 |B|를 그냥 더할 때", "|A ∩ B|만 볼 때", "|A - B|만 볼 때", "전체집합을 지울 때"],
      correctIndex: 0,
      explanation: "겹친 원소는 |A|에도, |B|에도 들어 있어 단순 합에서 두 번 세어집니다.",
      conceptTags: ["중복 세기"],
      questionType: "double-counting",
    },
    {
      prompt: "세 집합 포함배제에서 마지막에 세 집합 교집합을 더하는 이유는?",
      choices: ["세 번 빼져서 한 번 다시 보정해야 하기 때문", "항상 0이기 때문", "두 집합 공식과 무관하기 때문", "원소 순서를 맞추기 위해"],
      correctIndex: 0,
      explanation: "세 집합 모두에 속한 원소는 빼는 과정에서 과하게 빠지므로 다시 더합니다.",
      conceptTags: ["세 집합 포함배제"],
      questionType: "three-sets",
    },
    {
      prompt: "검색 필터 A 또는 B의 결과 수를 합칠 때 조심할 점은?",
      choices: ["두 필터에 모두 걸린 항목 중복", "항목 이름 길이", "정렬 방향", "페이지 색상"],
      correctIndex: 0,
      explanation: "A와 B에 모두 포함된 항목을 두 번 세지 않도록 보정해야 합니다.",
      conceptTags: ["검색 필터", "중복"],
      questionType: "cs-context",
    },
    {
      prompt: "포함배제가 특히 필요한 문제 신호는?",
      choices: ["겹치는 조건을 합쳐 세야 한다.", "원소 순서를 모두 나열한다.", "그래프 최단 경로를 구한다.", "문자열을 뒤집는다."],
      correctIndex: 0,
      explanation: "조건들이 겹치고 그 합집합 크기를 세야 할 때 포함배제가 필요합니다.",
      conceptTags: ["포함배제", "문제 판별"],
      questionType: "pattern-recognition",
    },
  ],
  "pigeonhole-principle": [
    {
      prompt: "상자 5개에 물건 11개를 넣으면 적어도 한 상자에는 몇 개 이상 들어가는가?",
      choices: ["3개", "2개", "5개", "11개"],
      correctIndex: 0,
      explanation: "ceil(11 / 5) = 3이므로 적어도 한 상자는 3개 이상입니다.",
      conceptTags: ["비둘기집 원리"],
      questionType: "ceil-count",
    },
    {
      prompt: "해시 충돌을 비둘기집 원리로 볼 수 있는 이유는?",
      choices: ["키 수가 버킷 수보다 많으면 같은 버킷이 생길 수밖에 없기 때문", "해시가 항상 정렬하기 때문", "버킷이 무한하기 때문", "키가 항상 문자열이기 때문"],
      correctIndex: 0,
      explanation: "대상이 상자보다 많으면 어느 상자에는 둘 이상 들어갑니다.",
      conceptTags: ["해시", "충돌"],
      questionType: "hash-collision",
    },
    {
      prompt: "비둘기집 원리는 무엇을 주로 보장하나?",
      choices: ["최소 하나의 겹침이나 집중", "정확한 위치", "모든 상자의 같은 개수", "항상 정렬된 순서"],
      correctIndex: 0,
      explanation: "구체적으로 어디인지는 몰라도 반드시 겹치거나 몰리는 곳이 있음을 보장합니다.",
      conceptTags: ["존재 보장"],
      questionType: "guarantee",
    },
    {
      prompt: "대상 n개를 상자 k개에 넣을 때 적어도 한 상자에 들어가는 최소 보장 개수는?",
      choices: ["ceil(n / k)", "n - k", "n + k", "k - n"],
      correctIndex: 0,
      explanation: "일반화된 비둘기집 원리는 ceil(n / k)를 보장합니다.",
      conceptTags: ["일반화"],
      questionType: "formula",
    },
    {
      prompt: "비둘기집 원리로 말할 수 없는 것은?",
      choices: ["어느 특정 상자에 반드시 들어가는지", "겹치는 상자가 존재하는지", "최소 몇 개가 몰리는지", "충돌이 피할 수 없는지"],
      correctIndex: 0,
      explanation: "원리는 존재를 보장하지만 특정 위치까지 항상 알려주지는 않습니다.",
      conceptTags: ["한계"],
      questionType: "limitation",
    },
    {
      prompt: "나머지 분류와 비둘기집 원리를 연결하면 상자는 보통 무엇인가?",
      choices: ["가능한 나머지 값", "원래 숫자의 이름", "코드 줄 수", "정렬된 인덱스만"],
      correctIndex: 0,
      explanation: "수를 나머지별로 분류하면 가능한 나머지 값들이 상자 역할을 합니다.",
      conceptTags: ["나머지", "분류"],
      questionType: "mod-buckets",
    },
  ],
  recurrences: [
    {
      prompt: "점화식과 닫힌 공식의 차이로 맞는 것은?",
      choices: ["점화식은 이전 값으로 현재 값을 정의한다.", "점화식은 항상 값 하나만 준다.", "닫힌 공식은 기저 사례가 필요 없다.", "둘은 항상 같은 표기다."],
      correctIndex: 0,
      explanation: "점화식은 이전 항과 규칙으로 다음 항을 만드는 정의입니다.",
      conceptTags: ["점화식"],
      questionType: "definition",
    },
    {
      prompt: "$a_1 = 2$, $a_n = a_{n-1} + 3$이면 $a_3$은?",
      choices: ["8", "5", "6", "11"],
      correctIndex: 0,
      explanation: "a2 = 5, a3 = 8입니다.",
      conceptTags: ["점화식 계산"],
      questionType: "sequence",
    },
    {
      prompt: "$T(n)=T(n-1)+n$에서 더해지는 n은 무엇과 가까운가?",
      choices: ["각 단계에서 추가로 하는 일", "항상 기저 사례", "정렬된 결과", "전체집합"],
      correctIndex: 0,
      explanation: "재귀 호출 외에 현재 단계에서 드는 비용을 나타냅니다.",
      conceptTags: ["점화식", "추가 비용"],
      questionType: "per-step-work",
    },
    {
      prompt: "분할 정복 점화식에서 $2T(n/2)$가 뜻하는 것은?",
      choices: ["절반 크기 문제 두 개", "같은 크기 문제 두 개", "문제 하나만", "기저 사례 두 개"],
      correctIndex: 0,
      explanation: "n/2 크기의 하위 문제를 두 번 푸는 구조입니다.",
      conceptTags: ["분할 정복"],
      questionType: "divide-and-conquer",
    },
    {
      prompt: "점화식을 펼치는 이유는?",
      choices: ["비용이 어떻게 누적되는지 보기 위해", "변수명을 바꾸기 위해", "항상 O(1)을 만들기 위해", "그래프를 그리기 위해서만"],
      correctIndex: 0,
      explanation: "몇 단계 펼치면 합이나 반복 구조가 드러납니다.",
      conceptTags: ["점화식 펼치기"],
      questionType: "unrolling",
    },
    {
      prompt: "피보나치 점화식의 대표 형태는?",
      choices: ["$F(n)=F(n-1)+F(n-2)$", "$F(n)=F(n)+1$", "$F(n)=n^2$", "$F(n)=0$"],
      correctIndex: 0,
      explanation: "피보나치는 앞의 두 항을 더해 다음 항을 만듭니다.",
      conceptTags: ["피보나치"],
      questionType: "fibonacci",
    },
  ],
  trees: [
    {
      prompt: "루트 노드의 의미는?",
      choices: ["트리의 시작이 되는 최상위 노드", "항상 리프 노드", "간선의 개수", "사이클의 시작점"],
      correctIndex: 0,
      explanation: "루트는 계층 구조에서 출발점이 되는 노드입니다.",
      conceptTags: ["트리", "루트"],
      questionType: "root",
    },
    {
      prompt: "부모-자식 관계가 잘 나타나는 CS 예시는?",
      choices: ["파일 시스템 디렉터리", "무작위 숫자 하나", "단일 boolean 값", "CPU 클럭"],
      correctIndex: 0,
      explanation: "파일 시스템은 폴더와 파일의 계층 구조로 볼 수 있습니다.",
      conceptTags: ["트리", "계층 구조"],
      questionType: "cs-context",
    },
    {
      prompt: "트리에 사이클이 있으면 왜 문제가 되는가?",
      choices: ["트리 정의를 깨뜨린다.", "간선 수가 반드시 0이 된다.", "모든 노드가 리프가 된다.", "루트가 항상 두 개가 된다."],
      correctIndex: 0,
      explanation: "트리는 사이클이 없는 연결 그래프입니다.",
      conceptTags: ["트리", "사이클"],
      questionType: "tree-definition",
    },
    {
      prompt: "후위 순회와 가장 가까운 순서는?",
      choices: ["자식들을 먼저 보고 부모를 나중에 본다.", "부모를 항상 먼저 본다.", "레벨 순서로만 본다.", "간선을 무시한다."],
      correctIndex: 0,
      explanation: "후위 순회는 하위 트리를 처리한 뒤 현재 노드를 처리합니다.",
      conceptTags: ["트리 순회", "후위 순회"],
      questionType: "postorder",
    },
    {
      prompt: "정점 n개인 트리의 간선 수가 n - 1인 이유와 가까운 감각은?",
      choices: ["사이클 없이 모두 연결하는 최소 연결 구조이기 때문", "모든 정점이 서로 직접 연결되기 때문", "간선이 없어야 하기 때문", "항상 방향 그래프이기 때문"],
      correctIndex: 0,
      explanation: "트리는 모든 정점을 연결하지만 사이클을 만들 만큼 간선을 더 갖지 않습니다.",
      conceptTags: ["트리", "간선 수"],
      questionType: "edge-count",
    },
    {
      prompt: "DFS가 트리 순회와 잘 맞는 이유는?",
      choices: ["한 가지를 깊게 내려갔다가 돌아오는 구조이기 때문", "항상 큐만 쓰기 때문", "레벨을 모두 동시에 보기 때문", "정점을 방문하지 않기 때문"],
      correctIndex: 0,
      explanation: "DFS는 재귀적으로 하위 트리를 내려가는 순회와 자연스럽게 연결됩니다.",
      conceptTags: ["DFS", "트리 순회"],
      questionType: "dfs",
    },
  ],
  "asymptotic-analysis": [
    {
      prompt: "$O(n \\log n)$과 자주 연결되는 알고리즘 예는?",
      choices: ["효율적인 정렬", "첫 원소 접근", "모든 부분집합 탐색", "상수 번 출력"],
      correctIndex: 0,
      explanation: "병합 정렬 같은 효율적인 비교 정렬은 O(n log n)과 자주 연결됩니다.",
      conceptTags: ["성장률", "정렬"],
      questionType: "growth-example",
    },
    {
      prompt: "공간복잡도에서 재귀 호출 스택을 고려해야 하는 이유는?",
      choices: ["호출이 쌓이면 추가 메모리를 쓰기 때문", "재귀는 시간이 없기 때문", "스택은 입력이 아니기 때문", "항상 O(0)이기 때문"],
      correctIndex: 0,
      explanation: "재귀 호출은 반환 전까지 스택 프레임을 쌓으므로 추가 공간이 됩니다.",
      conceptTags: ["공간복잡도", "재귀 스택"],
      questionType: "space-complexity",
    },
  ],
  "recursion-recurrences": [
    {
      prompt: "한 줄로 이어지는 재귀와 가지처럼 퍼지는 재귀를 가르는 핵심은?",
      choices: ["한 호출이 만드는 재귀 호출 수", "함수 이름 길이", "주석 수", "반환 타입 이름"],
      correctIndex: 0,
      explanation: "한 호출이 몇 개의 재귀 호출을 만드는지가 호출 트리 모양을 크게 바꿉니다.",
      conceptTags: ["재귀 호출 수"],
      questionType: "branching",
    },
    {
      prompt: "재귀 트리에서 전체 비용을 볼 때 함께 보는 것은?",
      choices: ["깊이와 각 레벨의 비용 합", "파일명과 확장자", "함수 이름과 변수 이름", "주석과 공백"],
      correctIndex: 0,
      explanation: "재귀 트리는 깊이와 레벨별 비용을 합쳐 전체 비용을 봅니다.",
      conceptTags: ["재귀 트리"],
      questionType: "recursion-tree",
    },
  ],
};

export function getSupplementalReviewQuestions(slug: string) {
  return supplementalReviewQuestions[slug] ?? [];
}

function rebalanceCorrectAnswerPosition(question: QuizQuestion, index: number): QuizQuestion {
  const targetCorrectIndex = index % question.choices.length;

  if (question.correctIndex === targetCorrectIndex) return question;

  const correctChoice = question.choices[question.correctIndex];
  const distractors = question.choices.filter((_, choiceIndex) => choiceIndex !== question.correctIndex);
  const choices = [...distractors];
  choices.splice(targetCorrectIndex, 0, correctChoice);

  return {
    ...question,
    choices: choices as QuizQuestion["choices"],
    correctIndex: targetCorrectIndex,
  };
}

export function normalizeReviewQuestions(slug: string, title: string, questions: QuizQuestion[]) {
  if (title !== "종합 점검") return questions;

  const merged = [...questions, ...getSupplementalReviewQuestions(slug)];
  return merged.slice(0, reviewQuestionCount).map(rebalanceCorrectAnswerPosition);
}
